/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AjoutUtilisateur (void);
GtkWidget* create_Espace_d_administrateur (void);
GtkWidget* create_GestionU (void);
GtkWidget* create_gestiondebureaudevote (void);
GtkWidget* create_Ajoutbv (void);
GtkWidget* create_Modification_du_bureau_de_vote (void);
GtkWidget* create_GestionSlim (void);
GtkWidget* create_Modifier_slim (void);
GtkWidget* create_AjoutSlim (void);
GtkWidget* create_SuppressionSlim (void);
GtkWidget* create_Observateur (void);
GtkWidget* create_ajouter_modifier_elections (void);
GtkWidget* create_tableau_d_elections (void);
GtkWidget* create_window1 (void);
GtkWidget* create_SUPPRIMER (void);
GtkWidget* create_MODIFIER (void);
GtkWidget* create_ObservateurSupprimer (void);
GtkWidget* create_SupprimerU (void);
GtkWidget* create_Modification_observateur (void);
