/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AjoutUtilisateur (void);
GtkWidget* create_GestionU (void);
GtkWidget* create_gestiondebureaudevote (void);
GtkWidget* create_Modification_du_bureau_de_vote (void);
GtkWidget* create_GestionSlim (void);
GtkWidget* create_Modifier_slim (void);
GtkWidget* create_AjoutSlim (void);
GtkWidget* create_SuppressionSlim (void);
GtkWidget* create_ajouter_modifier_elections (void);
GtkWidget* create_tableau_d_elections (void);
GtkWidget* create_window1 (void);
GtkWidget* create_SUPPRIMER (void);
GtkWidget* create_MODIFIER (void);
GtkWidget* create_ModifierU (void);
GtkWidget* create_Eadmin (void);
GtkWidget* create_statsU (void);
GtkWidget* create_ajouter_bv (void);
GtkWidget* create_afficherbv (void);
GtkWidget* create_window_calcul (void);
GtkWidget* create_menu_election (void);
GtkWidget* create_window_recherelect (void);
GtkWidget* create_window_election (void);
GtkWidget* create_window_ajouter_election (void);
GtkWidget* create_STATS (void);
GtkWidget* create_STATS2 (void);
GtkWidget* create_Login (void);
GtkWidget* create_ajouto (void);
GtkWidget* create_modifiero (void);
GtkWidget* create_suppo (void);
GtkWidget* create_chercheo (void);
GtkWidget* create_lobservateur (void);
GtkWidget* create_Election_Electorale (void);
