/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include"utilisateur.h"

int
main (int argc, char *argv[])
{
  GtkWidget *AjoutUtilisateur;
  GtkWidget *Espace_d_administrateur;
  GtkWidget *GestionU;
  GtkWidget *ModifierU;
  GtkWidget *gestiondebureaudevote;
  GtkWidget *Ajoutbv;
  GtkWidget *Modification_du_bureau_de_vote;
  GtkWidget *GestionSlim;
  GtkWidget *Modifier_slim;
  GtkWidget *AjoutSlim;
  GtkWidget *SuppressionSlim;
  GtkWidget *Observateur;
  GtkWidget *ajouter_modifier_elections;
  GtkWidget *tableau_d_elections;
  GtkWidget *window1;
  GtkWidget *SUPPRIMER;
  GtkWidget *MODIFIER;
  GtkWidget *ObservateurSupprimer;
  GtkWidget *SupprimerU;
  GtkWidget *Modification_observateur;
  GtkWidget *afficherbv;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   

  AjoutUtilisateur = create_AjoutUtilisateur ();
  gtk_widget_show (AjoutUtilisateur);
 
 Ajoutbv = create_ajouter_bv ();
  gtk_widget_show (Ajoutbv);
*/
 Espace_d_administrateur = create_Eadmin();
  gtk_widget_show (Espace_d_administrateur);
/*
afficherbv = create_afficherbv ();
  gtk_widget_show (afficherbv);
 

  GestionU = create_GestionU ();
  gtk_widget_show (GestionU);

  ModifierU = create_ModifierU ();
  gtk_widget_show (ModifierU);
 
  gestiondebureaudevote = create_gestiondebureaudevote ();
  gtk_widget_show (gestiondebureaudevote);
 
  Modification_du_bureau_de_vote = create_Modification_du_bureau_de_vote ();
  gtk_widget_show (Modification_du_bureau_de_vote);
  GestionSlim = create_GestionSlim ();
  gtk_widget_show (GestionSlim);
  Modifier_slim = create_Modifier_slim ();
  gtk_widget_show (Modifier_slim);
  AjoutSlim = create_AjoutSlim ();
  gtk_widget_show (AjoutSlim);
  SuppressionSlim = create_SuppressionSlim ();
  gtk_widget_show (SuppressionSlim);
  Observateur = create_Observateur ();
  gtk_widget_show (Observateur);
  ajouter_modifier_elections = create_ajouter_modifier_elections ();
  gtk_widget_show (ajouter_modifier_elections);
  tableau_d_elections = create_tableau_d_elections ();
  gtk_widget_show (tableau_d_elections);
  window1 = create_window1 ();
  gtk_widget_show (window1);
  SUPPRIMER = create_SUPPRIMER ();
  gtk_widget_show (SUPPRIMER);
  MODIFIER = create_MODIFIER ();
  gtk_widget_show (MODIFIER);
  ObservateurSupprimer = create_ObservateurSupprimer ();
  gtk_widget_show (ObservateurSupprimer);
  SupprimerU = create_SupprimerU ();
  gtk_widget_show (SupprimerU);
  Modification_observateur = create_Modification_observateur ();
  gtk_widget_show (Modification_observateur);

*/
  gtk_main ();
  return 0;
}

